KukaButtonGymEnv-v0:
  # Base path to SRL log folder
  log_folder: srl_zoo/logs/kuka_test/
  # Path to the different trained SRL models
  autoencoder: 18-07-04_11h08_38_mlp_ST_DIM2_autoencoder/srl_model.pth
  vae: 18-07-04_11h08_56_mlp_ST_DIM2_vae/srl_model.pth
  supervised: baselines/supervised_custom_cnn_SEED1_EPOCHS25_BS32/srl_supervised_model.pth
  pca: baselines/pca_ST_DIM5/pca.pkl
  robotic_priors: 18-07-04_11h01_51_custom_cnn_ST_DIM3_priors/srl_model.pth
  inverse: 18-06-20_16h36_48_custom_cnnST_DIM2_inverse/srl_model.pth
  forward: 18-06-20_16h36_48_custom_cnnST_DIM2_forward/srl_model.pth
  multi_view_srl: 18-07-04_11h06_09_custom_cnn_ST_DIM10_priors/srl_model.pth
  srl_combination: 18-06-20_16h36_48_custom_cnnST_DIM2_forward_reward_inverse_autoencoder/srl_model.pth

Kuka2ButtonGymEnv-v0:
  # Base path to SRL log folder
  log_folder: srl_zoo/logs/kuka_2_button/
  # Path to the different trained SRL models
  autoencoder: 18-07-04_11h08_38_mlp_ST_DIM2_autoencoder/srl_model.pth
  vae: 18-07-04_11h08_56_mlp_ST_DIM2_vae/srl_model.pth
  supervised: baselines/supervised_custom_cnn_SEED1_EPOCHS25_BS32/srl_supervised_model.pth
  pca: baselines/pca_ST_DIM32/pca.pkl
  robotic_priors: 18-07-04_11h01_51_custom_cnn_ST_DIM3_priors/srl_model.pth
  inverse: 18-06-20_16h36_48_custom_cnnST_DIM2_inverse/srl_model.pth
  forward: 18-06-20_16h36_48_custom_cnnST_DIM2_forward/srl_model.pth
  multi_view_srl: 18-07-04_11h06_09_custom_cnn_ST_DIM10_priors/srl_model.pth
  srl_combination: 18-06-20_16h36_48_custom_cnnST_DIM2_forward_reward_inverse_autoencoder/srl_model.pth

KukaRandButtonGymEnv-v0:
  # Base path to SRL log folder
  log_folder: srl_zoo/logs/kuka_rand_button/
  # Path to the different trained SRL models
  autoencoder: 18-07-04_11h08_38_mlp_ST_DIM2_autoencoder/srl_model.pth
  vae: 18-07-04_11h08_56_mlp_ST_DIM2_vae/srl_model.pth
  supervised: baselines/supervised_custom_cnn_SEED1_EPOCHS25_BS32/srl_supervised_model.pth
  pca: baselines/pca_ST_DIM10/pca.pkl
  robotic_priors: 18-07-04_11h01_51_custom_cnn_ST_DIM3_priors/srl_model.pth
  inverse: 18-06-20_16h36_48_custom_cnnST_DIM2_inverse/srl_model.pth
  forward: 18-06-20_16h36_48_custom_cnnST_DIM2_forward/srl_model.pth
  multi_view_srl: 18-07-04_11h06_09_custom_cnn_ST_DIM10_priors/srl_model.pth
  srl_combination: 18-06-20_16h36_48_custom_cnnST_DIM2_forward_reward_inverse_autoencoder/srl_model.pth

KukaMovingButtonGymEnv-v0:
  # Base path to SRL log folder
  log_folder: srl_zoo/logs/kuka_moving_button_big/
  # Path to the different trained SRL models
  autoencoder: 18-07-04_11h08_38_mlp_ST_DIM2_autoencoder/srl_model.pth
  vae: 18-07-04_11h08_56_mlp_ST_DIM2_vae/srl_model.pth
  supervised: baselines/supervised_custom_cnn_SEED1_EPOCHS25_BS32/srl_supervised_model.pth
  pca: baselines/pca_ST_DIM32/pca.pkl
  robotic_priors: 18-07-04_11h01_51_custom_cnn_ST_DIM3_priors/srl_model.pth
  inverse: 18-06-20_16h36_48_custom_cnnST_DIM2_inverse/srl_model.pth
  forward: 18-06-20_16h36_48_custom_cnnST_DIM2_forward/srl_model.pth
  multi_view_srl: 18-07-04_11h06_09_custom_cnn_ST_DIM10_priors/srl_model.pth
  srl_combination: 18-06-20_16h36_48_custom_cnnST_DIM2_forward_reward_inverse_autoencoder/srl_model.pth

MobileRobotGymEnv-v0:
  # Base path to SRL log folder
  log_folder: srl_zoo/logs/mobile_robot_walls/
  # Path to the different trained SRL models
  autoencoder: 18-07-04_11h08_38_mlp_ST_DIM2_autoencoder/srl_model.pth
  vae: 18-07-04_11h08_56_mlp_ST_DIM2_vae/srl_model.pth
  supervised: baselines/supervised_resnet_SEED1_EPOCHS25_BS32/srl_supervised_model.pth
  pca: baselines/pca_ST_DIM32/pca.pkl
  robotic_priors: 18-07-04_11h01_51_custom_cnn_ST_DIM3_priors/srl_model.pth
  inverse: 18-06-20_16h36_48_custom_cnnST_DIM2_inverse/srl_model.pth
  forward: 18-06-20_16h36_48_custom_cnnST_DIM2_forward/srl_model.pth
  multi_view_srl: 18-07-04_11h06_09_custom_cnn_ST_DIM10_priors/srl_model.pth
  srl_combination: 18-06-20_16h36_48_custom_cnnST_DIM2_forward_reward_inverse_autoencoder/srl_model.pth

MobileRobot2TargetGymEnv-v0:
  # Base path to SRL log folder
  log_folder: srl_zoo/logs/mobile_robot_2target/
  # Path to the different trained SRL models
  autoencoder: 18-07-04_11h08_38_mlp_ST_DIM2_autoencoder/srl_model.pth
  vae: 18-07-04_11h08_56_mlp_ST_DIM2_vae/srl_model.pth
  supervised: baselines/supervised_resnet_SEED1_EPOCHS25_BS32/srl_supervised_model.pth
  pca: baselines/pca_ST_DIM32/pca.pkl
  robotic_priors: 18-07-04_11h01_51_custom_cnn_ST_DIM3_priors/srl_model.pth
  inverse: 18-06-20_16h36_48_custom_cnnST_DIM2_inverse/srl_model.pth
  forward: 18-06-20_16h36_48_custom_cnnST_DIM2_forward/srl_model.pth
  multi_view_srl: 18-07-04_11h06_09_custom_cnn_ST_DIM10_priors/srl_model.pth
  srl_combination: 18-06-20_16h36_48_custom_cnnST_DIM2_forward_reward_inverse_autoencoder/srl_model.pth

MobileRobot1DGymEnv-v0:
  # Base path to SRL log folder
  log_folder: srl_zoo/logs/mobile_robot_slider/
  # Path to the different trained SRL models
  autoencoder: 18-07-04_11h08_38_mlp_ST_DIM2_autoencoder/srl_model.pth
  vae: 18-07-04_11h08_56_mlp_ST_DIM2_vae/srl_model.pth
  supervised: baselines/supervised_resnet_SEED1_EPOCHS25_BS32/srl_supervised_model.pth
  pca: baselines/pca_ST_DIM32/pca.pkl
  robotic_priors: 18-07-04_11h01_51_custom_cnn_ST_DIM3_priors/srl_model.pth
  inverse: 18-06-20_16h36_48_custom_cnnST_DIM2_inverse/srl_model.pth
  forward: 18-06-20_16h36_48_custom_cnnST_DIM2_forward/srl_model.pth
  multi_view_srl: 18-07-04_11h06_09_custom_cnn_ST_DIM10_priors/srl_model.pth
  srl_combination: 18-06-20_16h36_48_custom_cnnST_DIM2_forward_reward_inverse_autoencoder/srl_model.pth

MobileRobotLineTargetGymEnv-v0:
  # Base path to SRL log folder
  log_folder: srl_zoo/logs/mobile_line_target/
  # Path to the different trained SRL models
  autoencoder: 18-07-04_11h08_38_mlp_ST_DIM2_autoencoder/srl_model.pth
  vae: 18-07-04_11h08_56_mlp_ST_DIM2_vae/srl_model.pth
  supervised: baselines/supervised_resnet_SEED1_EPOCHS25_BS32/srl_supervised_model.pth
  pca: baselines/pca_ST_DIM32/pca.pkl
  robotic_priors: 18-07-04_11h01_51_custom_cnn_ST_DIM3_priors/srl_model.pth
  inverse: 18-06-20_16h36_48_custom_cnnST_DIM2_inverse/srl_model.pth
  forward: 18-06-20_16h36_48_custom_cnnST_DIM2_forward/srl_model.pth
  multi_view_srl: 18-07-04_11h06_09_custom_cnn_ST_DIM10_priors/srl_model.pth
  srl_combination: 18-06-20_16h36_48_custom_cnnST_DIM2_forward_reward_inverse_autoencoder/srl_model.pth

CarRacingGymEnv-v0:
  # Base path to SRL log folder
  log_folder: srl_zoo/logs/car_racing/
  # Path to the different trained SRL models
  autoencoder: 18-07-04_11h08_38_mlp_ST_DIM2_autoencoder/srl_model.pth
  vae: 18-07-04_11h08_56_mlp_ST_DIM2_vae/srl_model.pth
  supervised: baselines/supervised_resnet_SEED1_EPOCHS25_BS32/srl_supervised_model.pth
  pca: baselines/pca_ST_DIM32/pca.pkl
  robotic_priors: 18-07-04_11h01_51_custom_cnn_ST_DIM3_priors/srl_model.pth
  inverse: 18-06-20_16h36_48_custom_cnnST_DIM2_inverse/srl_model.pth
  forward: 18-06-20_16h36_48_custom_cnnST_DIM2_forward/srl_model.pth
  multi_view_srl: 18-07-04_11h06_09_custom_cnn_ST_DIM10_priors/srl_model.pth
  srl_combination: 18-07-09_16h34_40_custom_cnn_ST_DIM3_vae_inverse/srl_model.pth
