# Base path to SRL log folder
log_folder: srl_priors/logs/kuka_test/
# Path to the different trained SRL models
autoencoder: baselines/autoencoder_cnn_ST_DIM6_SEED1_NOISE0_1_EPOCHS25_BS32/srl_ae_model.pth
vae: baselines/vae_cnn_ST_DIM6_SEED1_NOISE0_EPOCHS25_BS32/srl_vae_model.pth
supervised: baselines/supervised_custom_cnn_SEED1_EPOCHS25_BS32/srl_supervised_model.pth
pca: baselines/pca_ST_DIM5/pca.pkl
srl_priors: 07-03-18_13h55_31_custom_cnn_ProTemCauRep_ST_DIM3_SEED0_priors/srl_model.pth
